# Generated by Django 4.1.7 on 2023-03-23 22:33

import art_vostorg.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ivent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "title_photo",
                    sorl.thumbnail.fields.ImageField(
                        blank=True,
                        null=True,
                        upload_to=art_vostorg.models.get_user_directory_path,
                        verbose_name="Фото",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Описание"),
                ),
                ("body", tinymce.models.HTMLField(verbose_name="Содержание")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
