# Generated by Django 4.1.7 on 2023-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("art_vostorg", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ivent",
            name="description",
            field=models.CharField(max_length=256, verbose_name="Описание"),
        ),
    ]
